# Generated by Django 2.0.2 on 2018-03-01 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('abv', models.FloatField(null=True)),
                ('ebc', models.IntegerField(null=True)),
                ('ibu', models.IntegerField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('imgsrc', models.CharField(default='https://cdn4.iconfinder.com/data/icons/proglyphs-food/512/Beer-512.png', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.Maker'),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beers.Style'),
        ),
    ]
