# Generated by Django 2.0.2 on 2018-03-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_beer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='rating',
            field=models.FloatField(editable=False, null=True),
        ),
    ]
