# Generated by Django 2.0.2 on 2018-04-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0005_auto_20180402_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='imgsrc',
            field=models.ImageField(upload_to='images/beers'),
        ),
    ]
