# Generated by Django 2.0.2 on 2018-02-26 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beerreviewsapp', '0003_auto_20180226_1847'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='maker',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='style',
            unique_together=set(),
        ),
    ]
