# Generated by Django 2.0.2 on 2018-02-27 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerreviewsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 2, 27, 14, 50, 23, 344)),
        ),
    ]
