# Generated by Django 2.0.2 on 2018-02-28 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerreviewsapp', '0002_auto_20180227_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 2, 28, 18, 11, 29, 975878)),
        ),
    ]
