# Generated by Django 2.0.2 on 2018-02-28 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beerreviewsapp', '0003_auto_20180228_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
