# Generated by Django 2.0.2 on 2018-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beerreviewsapp', '0004_auto_20180228_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='abv',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='beer',
            name='ibu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beer',
            name='ebc',
            field=models.IntegerField(null=True),
        ),
    ]
