# Generated by Django 2.0.2 on 2018-02-26 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ebc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('beer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerreviewsapp.Beer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='beer',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerreviewsapp.Country'),
        ),
        migrations.AddField(
            model_name='beer',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerreviewsapp.Maker'),
        ),
        migrations.AddField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beerreviewsapp.Style'),
        ),
    ]
