# Generated by Django 2.0.2 on 2018-02-26 17:47

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beerreviewsapp', '0002_auto_20180226_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='beer',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
